### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by SmithaShivakumar** [DoodlingDev/Dots-Quest-Legend#27]
Hi Ajina,

I am not sure if you remmeber but we had met during the baseball hackday 2 weeks ago. I am currently working on a javascript(with R) project and I wanted to know if I could consult you through email with a few issues I have. Look forward to hearing back from you!

Best Regards
Smitha

**Comment by DoodlingDev** [comment]
omg I'm so sorry I spaced on you again. My email is aji.slater@gmail.com. unfortunately the answer as to how I was doing the javascript work with the RStudio stuff wasn't a workable solution, like you couldn't have written any code into it, it was just hacked in through the browser js console.

**Comment by SmithaShivakumar** [comment]
No worries and I see!
